game_title: "EConeNinja"
hyperloop_audio_path: "/Users/hassen/local_Dev/GAMES/sample_pygame/assets/audio/music/hyperloop.mp3"
screen:
  width: 800
  height: 600
clock_tick_rate: 60
projectile_timer_interval: 5000
difficulty_timer_interval: 30000
difficulty_update_value: 5000
debug_mode: true 
